/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/Accordion.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    ButtonGroup: typeof import('./src/components/ButtonGroup.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    CheckboxGroup: typeof import('./src/components/CheckboxGroup.vue')['default']
    copy: typeof import('./src/components/Button copy.vue')['default']
    Datepicker: typeof import('./src/components/Datepicker.vue')['default']
    Disclosure: typeof import('./src/components/Disclosure.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    DropdownItem: typeof import('./src/components/DropdownItem.vue')['default']
    IconMdiAccount: typeof import('~icons/mdi/account')['default']
    IconMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IconMdiLightChevronDown: typeof import('~icons/mdi-light/chevron-down')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Popover: typeof import('./src/components/Popover.vue')['default']
    Radio: typeof import('./src/components/Radio.vue')['default']
    RadioGroup: typeof import('./src/components/RadioGroup.vue')['default']
    SecureField: typeof import('./src/components/SecureField.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TextEditor: typeof import('./src/components/TextEditor.vue')['default']
    TextField: typeof import('./src/components/TextField.vue')['default']
    Toggle: typeof import('./src/components/Toggle.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
  }
  export interface ComponentCustomProperties {
    OnClickOutside: typeof import('@vueuse/components')['vOnClickOutside']
  }
}
