/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Action: typeof import('./src/components/Action.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Badge: typeof import('./src/components/Badge.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    CheckboxGroup: typeof import('./src/components/CheckboxGroup.vue')['default']
    Chip: typeof import('./src/components/Chip.vue')['default']
    Datepicker: typeof import('./src/components/Datepicker.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    DocsLayout: typeof import('./src/components/DocsLayout.vue')['default']
    FloatingUi: typeof import('./src/components/FloatingUi.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuContent: typeof import('./src/components/MenuContent.vue')['default']
    MenuDivider: typeof import('./src/components/MenuDivider.vue')['default']
    MenuHeader: typeof import('./src/components/MenuHeader.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    Paginator: typeof import('./src/components/Paginator.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    Prose: typeof import('./src/components/Prose.vue')['default']
    Radio: typeof import('./src/components/Radio.vue')['default']
    RadioGroup: typeof import('./src/components/RadioGroup.vue')['default']
    RichTextEditor: typeof import('./src/components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrollspy: typeof import('./src/components/Scrollspy.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
    Sheet: typeof import('./src/components/Sheet.vue')['default']
    Slider: typeof import('./src/components/Slider.vue')['default']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
    Switch: typeof import('./src/components/Switch.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TabPanel: typeof import('./src/components/TabPanel.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    TextEditor: typeof import('./src/components/TextEditor.vue')['default']
    TextField: typeof import('./src/components/TextField.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
    Tree: typeof import('./src/components/Tree.vue')['default']
    TreeItem: typeof import('./src/components/TreeItem.vue')['default']
  }
}
