/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/action-component': RouteRecordInfo<'/action-component', '/action-component', Record<never, never>, Record<never, never>>,
    '/avatar-component': RouteRecordInfo<'/avatar-component', '/avatar-component', Record<never, never>, Record<never, never>>,
    '/badge-component': RouteRecordInfo<'/badge-component', '/badge-component', Record<never, never>, Record<never, never>>,
    '/card-component': RouteRecordInfo<'/card-component', '/card-component', Record<never, never>, Record<never, never>>,
    '/checkbox-component': RouteRecordInfo<'/checkbox-component', '/checkbox-component', Record<never, never>, Record<never, never>>,
    '/checkboxgroup-component': RouteRecordInfo<'/checkboxgroup-component', '/checkboxgroup-component', Record<never, never>, Record<never, never>>,
    '/chip-component': RouteRecordInfo<'/chip-component', '/chip-component', Record<never, never>, Record<never, never>>,
    '/dialog-component': RouteRecordInfo<'/dialog-component', '/dialog-component', Record<never, never>, Record<never, never>>,
    '/menu-component': RouteRecordInfo<'/menu-component', '/menu-component', Record<never, never>, Record<never, never>>,
    '/progress-component': RouteRecordInfo<'/progress-component', '/progress-component', Record<never, never>, Record<never, never>>,
    '/prose-component': RouteRecordInfo<'/prose-component', '/prose-component', Record<never, never>, Record<never, never>>,
    '/radio-component': RouteRecordInfo<'/radio-component', '/radio-component', Record<never, never>, Record<never, never>>,
    '/radiogroup-component': RouteRecordInfo<'/radiogroup-component', '/radiogroup-component', Record<never, never>, Record<never, never>>,
    '/select-component': RouteRecordInfo<'/select-component', '/select-component', Record<never, never>, Record<never, never>>,
    '/switch-component': RouteRecordInfo<'/switch-component', '/switch-component', Record<never, never>, Record<never, never>>,
    '/texteditor-component': RouteRecordInfo<'/texteditor-component', '/texteditor-component', Record<never, never>, Record<never, never>>,
    '/textfield-component': RouteRecordInfo<'/textfield-component', '/textfield-component', Record<never, never>, Record<never, never>>,
    '/tooltip-component': RouteRecordInfo<'/tooltip-component', '/tooltip-component', Record<never, never>, Record<never, never>>,
  }
}
